name: format

on: pull_request

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.0' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo
          coverage: xdebug
          tools: php-cs-fixer, composer:v2

      - name: PHP CS Fixer
        run: php-cs-fixer fix --config .php_cs.dist

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Apply PHP CS Fixer changes
          branch: ${{ github.head_ref }}